import Vue from 'vue';

import Vuetify, {
  VAlert,
  VAvatar,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VContainer,
  VContent,
  VForm,
  VSelect,
  VTextField,
  VBtn,
  VFabTransition,
  VCard,
  VCardText,
  VCardActions,
  VCardTitle,
  VLayout,
  VFlex,
  VDialog,
  VNavigationDrawer,
  VSubheader,
  VIcon,
  VList,
  VListGroup,
  VListItem,
  VListItemAction,
  VListItemActionText,
  VListItemAvatar,
  VListItemContent,
  VListItemGroup,
  VListItemIcon,
  VListItemSubtitle,
  VListItemTitle,
  VTooltip,
  VToolbar,
  VToolbarTitle,
  VToolbarItems,
  VSpacer,
  VDataTable,
  VDivider,
  VSnackbar,
  VCheckbox,
  VTextarea,
  VProgressLinear,
  VProgressCircular,
  VDatePicker,
  VTimePicker,
  VMenu,
  VBadge,
  VTabs,
  VTab,
  VTabItem,
  VTabsSlider,
  VFadeTransition,
  VImg,
  VCombobox,
  VChip,
  VPagination,
  VAutocomplete,
  VExpansionPanel,
  VExpansionPanelContent,
  VResponsive,
  VItemGroup,
  VBreadcrumbs,
  VRadioGroup,
  VRadio,
} from 'vuetify/lib'

Vue.use(Vuetify, {
  theme: {
    primary: "#3B125F",
    secondary: "8B5FBF",
    accent: "#BF653F",
    error: "#722530",
    warning: "#A37513",
    info: "#396893",
    success: "#4CAF50"
  },
  components: {
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAvatar,
    VContent,
    VContainer,
    VTextField,
    VTextarea,
    VForm,
    VSelect,
    VAlert,
    VBtn,
    VFabTransition,
    VCard,
    VCardText,
    VLayout,
    VFlex,
    VDialog,
    VNavigationDrawer,
    VSubheader,
    VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemActionText,
    VListItemAvatar,
    VListItemContent,
    VListItemGroup,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VIcon,
    VTooltip,
    VToolbar,
    VToolbarTitle,
    VToolbarItems,
    VSpacer,
    VCardActions,
    VCardTitle,
    VDataTable,
    VDivider,
    VSnackbar,
    VCheckbox,
    VProgressLinear,
    VProgressCircular,
    VDatePicker,
    VTimePicker,
    VMenu,
    VBadge,
    VTabs,
    VTab,
    VTabItem,
    VTabsSlider,
    VFadeTransition,
    VImg,
    VCombobox,
    VChip,
    VPagination,
    VAutocomplete,
    VExpansionPanel,
    VExpansionPanelContent,
    VResponsive,
    VItemGroup,
    VBreadcrumbs,
    VRadioGroup,
    VRadio,
  }
});

export default new Vuetify({
  icons: {
    iconfont: 'mdi',
  },
});
